# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "splintable"
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Ahmed El.Hussaini"]
  s.date = "2013-02-25"
  s.description = "Splintable is a ruby library for generating readable content from urls or links similar to Pocket"
  s.email = "aelhussaini@gmail.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = Dir["{lib,test}/**/*"] + ["Gemfile", "LICENSE.txt", "README.doc", "Rakefile", "VERSION"]
  #s.files = [
  #  ".document",
  #  "Gemfile",
  #  "LICENSE.txt",
  #  "README.rdoc",
  #  "Rakefile",
  #  "VERSION",
  #  "lib/splintable/generators/url_generator.rb",
  #  "test/helper.rb",
  #  "test/test_splintable.rb"
  #]
  s.homepage = "http://github.com/sandboxws/splintable"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.24"
  s.summary = "Splintable is a ruby library for generating readable content from urls or links similar to Pocket"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_development_dependency(%q<bundler>, [">= 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.8.4"])
    else
      s.add_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_dependency(%q<bundler>, [">= 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.8.4"])
      s.add_dependency(%q<mechanize>, ["~> 2.5.1"])
      s.add_dependency(%q<postrank-uri>, ["~> 1.0.17"])
      s.add_dependency(%q<fastimage>, ["~> 1.2.13"])
    end
  else
    s.add_dependency(%q<rdoc>, ["~> 3.12"])
    s.add_dependency(%q<bundler>, [">= 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.8.4"])
    s.add_dependency(%q<mechanize>, ["~> 2.5.1"])
    s.add_dependency(%q<postrank-uri>, ["~> 1.0.17"])
    s.add_dependency(%q<fastimage>, ["~> 1.2.13"])
  end
end

